#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Tue May 17 16:17:01 2016
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
import client
import threading
import asyncore
import Queue

# to_network = Queue.Queue()
# def loop():
#     while 1:
#         while not to_network.empty():
#             message = to_network.get()
#             #process and handle message
#             #
#             #remember to validate any possible
#             #socket objects recieved from the GUI,
#             #they could already be closed
#         asyncore.poll(timeout=.01)

class MainFrame(wx.Frame):
    def __init__(self, parent, id, user=''):
        # begin wxGlade: MainFrame.__init__
        wx.Frame.__init__(self, parent, id, user)
        print user
        self.label_1 = wx.StaticText(self, wx.ID_ANY, user)
        self.label_2 = wx.StaticText(self, wx.ID_ANY, u"\u5728\u7ebf\u7528\u6237:")
        self.control = wx.TextCtrl(self, style=wx.TE_MULTILINE)
        self.control2 = wx.TextCtrl(self, style=wx.TE_MULTILINE)
        self.button = wx.Button(self, wx.ID_ANY, u'发送')
        

        self.__set_properties()
        self.__do_layout()
#         self.__bind_event()
        # end wxGlade
        
        client.Client('localhost', 8080, self)
        cc = threading.Thread(name='client', target=asyncore.loop)
        cc.setDaemon(True)
        cc.start()

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("gtalk")
        self.SetSize((360, 700))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.label_1.SetMinSize((150, 30))
        self.label_1.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_2.SetMinSize((80, 23))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.label_1, 0, wx.LEFT | wx.TOP, 48)
        sizer_3.Add(self.label_2, 0, 0, 0)
        sizer_3.Add(self.control, 1, wx.EXPAND)
        sizer_3.Add(self.control2, 1, wx.EXPAND)
        sizer_3.Add(self.button, 0, wx.LEFT, 10)
        sizer_2.Add(sizer_3, 1, 0, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade
        self.CenterOnScreen()
    
#     def __bind_event(self):
#         self.button.Bind(wx.EVT_BUTTON, self.OnSend)
#     
#     def OnSend(self, event):
#         if self.control2.GetValue():
#             message = self.control2.GetValue() + "**end**"
#         self.control2.SetValue('')
#         
        
        

# end of class MainFrame
if __name__ == '__main__':
    app = wx.App(False)
    frame = MainFrame(None, -1)
    frame.Show()
    app.MainLoop()
